### ISSUE TITLE
Missing build-tool-depends on c2hs

### ISSUE THREAD

**Issue by kirelagin** [k0001/hs-libsodium#2]
The library fails to build because it requires `c2hs` and the dependency is not declared.

**Comment by k0001** [comment]
As mentioned in 0bc96db:

> Notice with this change, `cabal` can't see the `c2hs` provided by Nix as specified through `libsodium/pkg.nix`'s `libraryToolDepends` and `testToolDepends`. This still needs solving.

**Comment by dminuoso** [comment]
@k0001 Hiya. Could you release fix this to hackage?

**Comment by kirelagin** [comment]
Hi @k0001, it would be great if you could upload this version to Hackage.
